### ISSUE TITLE
Cannot "edit" forum posts

### ISSUE THREAD

**Issue by nlourenco** [chriscoyier/CSS-Tricks-v10#1]
User cannot "edit" forum posts from thread view.

**Comment by KittyGiraudel** [comment]
Seconded. Cannot edit a forum comment.

**Comment by chriscoyier** [comment]
Confirmed. Suck. The URL of the link is correct, but unclickable. Very weird JS error it must be.

**Comment by chriscoyier** [comment]
Fixed.
