### ISSUE TITLE
Browser Compatibility 

### ISSUE THREAD

**Issue by Luxbit** [chriscoyier/CSS-Tricks-v10#102]
I just wanted to ask you if you are aware of the fact that with the new design IE 8 isn't supported anymore. The Main Menubar is missing etc. I think that is due to the new HTML 5 tags like <header> etc... 

Best regards

**Comment by chriscoyier** [comment]
I should probably toss in the HTML5 shiv. But yeah, official browser support is IE 9+. Perhaps I should list that somewhere as well to make it official.

**Comment by chriscoyier** [comment]
HTML5 shiv didn't help much for IE 8. I just yanked all styling for IE 8 and down.

**Comment by Luxbit** [comment]
Yeah I tried this myself to get my HTML5 Games working in older browsers :( How many people actually use IE8? Those will become even less with the release of Win8, even if it's horrible on Desktops.... I only came across that problem while playing around with BrowserStack. People interested in web design  usually browse using Chrome or Firefox.
