### ISSUE TITLE
forums on mobile VERY weird

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/CSS-Tricks-v10#106]

**Comment by KittyGiraudel** [comment]
Tried on my Samsung Galaxy SII (default browser) tonight, and it was a total mess. I couldn't use the forums at all since comments wasn't displayed, layout was completely broken, and some other various bugs.

**Comment by chriscoyier** [comment]
Still a huge mystery. I need to get some remote web inspector stuff going on so I can see where it's getting the old templates from (but only partially old templates). I thought I was on to something as I found some old cache and nuked it, but still nothing. 

The big hint is the "Howdy Stranger" text. That's ONLY the previous design. But it's showing it on mobile devices in the forums. So strange.

**Comment by KittyGiraudel** [comment]
The pagination seems weird as well. I mean, not like the v10 pagination. I can see <1234567...573>, which is, if no mistake, the v9 pagination.

If you want me to do more test, just ask. :)

**Comment by chriscoyier** [comment]
I think I fixed this.
