### ISSUE TITLE
text breaks

### ISSUE THREAD

**Issue by norcross** [chriscoyier/CSS-Tricks-v10#11]
On the announcement page (which is slick as hell, BTW), a few spots have words breaking without a hyphen. Here's a screenshot http://imgur.com/GF1ox

Details:

browser: Firefox 15
OS: Windows 7
Screen res: 1920x1080

**Comment by coogie** [comment]
+1

Really breaks the flow when you're reading

**Comment by chriscoyier** [comment]
HUGE differences across platforms and and versions of firefox apparently. 15 on mac isn't that bad. Fix going out for it now.
