### ISSUE TITLE
Lodge Videos aren't loading on iPad

### ISSUE THREAD

**Issue by justrjlewis** [chriscoyier/CSS-Tricks-v10#117]
I've tried to load the v10 video on my ipad and seem to be receiving no data....The "loading" indicator just cycles.  It loads extremely quickly on my iMac.  

I tried them on both Safari and Chrome, with a reload...the videos would not play.

http://cl.ly/image/2N0a0E1I1e2b

**Comment by chriscoyier** [comment]
I can confirm this on video #2. Trying to re-export now. In general videos should work on iPad, so perhaps skip this one for now.

**Comment by chriscoyier** [comment]
I deleted it, re-exported it, used the same settings as every other video, and still the same problem. It's only 11:12 long  and 223 MB, so fairly average in length/size. 

I just tried #1 and #6 and they fail as well. 

SO... it looks like a file size issue. Around 200MB seems like the maximum before failure.

Other issues detailed here: http://blog.millermedeiros.com/html5-video-issues-on-the-ipad-and-how-to-solve-them/

Not sure how I'm going to deal with it yet.

**Comment by chriscoyier** [comment]
Still broken = 4, 5, 6, 7, 8, 9, 10, well crap just about all of them up to where I am. Will be reexporting smaller versions today and making work. I have a method I put in place to serve smaller file sizes to ipad which seems to be working.

**Comment by chriscoyier** [comment]
DONE
