### ISSUE TITLE
Bounce animation on Lodge login

### ISSUE THREAD

**Issue by dsparks83** [chriscoyier/CSS-Tricks-v10#122]
On the lodge login page if you enter the incorrect details you get the normal wordpress left-right bounce on the login box. However due to the way the page is styled it looks rather weird because the links at the bottom of the box don't bounce with the login fields. Try it and you'll probably see what I mean.
Not really a bug of sorts or a huge issue and it may well be intentional, but it looks strange to me - I should probably just stop forgetting my password and I wouldn't see it anyway!

**Comment by chriscoyier** [comment]
ha yeah, I just saw that. I don't think it's that big of a deal stylistically I think I'll just let it be.
