### ISSUE TITLE
Problem with videos on Windows Phone 7.5 

### ISSUE THREAD

**Issue by MaximOrlovsky** [chriscoyier/CSS-Tricks-v10#127]
Since episode #113 is not possible to play videos on Windows Phone 7.5. 
I subscribed via Microsoft Marketplace in Podcasts section.

The error: "Sorry, we can't play this file on your phone"

Episode #112 works great.

**Comment by chriscoyier** [comment]
Hopefully switching to a new player AGAIN to solve this.
