### ISSUE TITLE
[Forums] No footer

### ISSUE THREAD

**Issue by KittyGiraudel** [chriscoyier/CSS-Tricks-v10#13]
There is no footer in the Forums section, but there is in any other section in the site. 

Little confusing but maybe it works as intented.

**Comment by chriscoyier** [comment]
Yahhh that's on purpose. I might put some kind of small footer down there. The footer on the rest of the site is largely focused around "me" - whereas the forums are all about you.

**Comment by chriscoyier** [comment]
Gonna push something up for this.
