### ISSUE TITLE
Forum in IE9

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#130]
The Forum looks pretty wonky in IE9....  I just looked and it defaults to 'quirks mode' so when i switch it back it is fine.  Not sure if you care about oldIE as most of us don't want to but preIE9 forums are pretty jacked up, actually so is the rest of the site.  I assume your stats for IE7/8 are low enough not to matter.

**Comment by senff** [comment]
Ha! No doctype declared at all?

Chris, Chris....... ;)

**Comment by chriscoyier** [comment]
Good catch!
