### ISSUE TITLE
Videos in FF/IE

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#131]
The videoes don't play in FF or IE9 on Win 7

**Comment by bkbillma** [comment]
In FF I got the video to play but skipping is insanely slow.  The video shows that it is fully loaded pretty quickly but trying to skip takes a minute or more.

**Comment by chriscoyier** [comment]
The videos in the regular area of the site are YouTube and I'm going to transition the Lodge into using Vimeo player. Should be better by the end of the week. Sorry about that.
