### ISSUE TITLE
IE 9 Crashing in snippets

### ISSUE THREAD

**Issue by aberson1** [chriscoyier/CSS-Tricks-v10#135]
When i go into snippets IE keeps crashing http://css-tricks.com/prevent-white-flash-iframe/ it happens no matter what i do.

**Comment by bkbillma** [comment]
Works fine on IE 9 for me.

**Comment by senff** [comment]
Same here, IE9 crashes on that specific page (not all, or any other, snippets).

**Comment by bkbillma** [comment]
Oh my bad.  Yeah the snippets work fine.  Other than that page

**Comment by bkbillma** [comment]
I checked the error logs and there doesn't seem to be any help/info about the crash.  The bit of binging/googling i have done it comes up as an access violation error but nothing I can find really seems to be similar problems.

Exception code: 0xc0000005

The error 0xC0000005 is generated by an illegal "memory access violation"  -- found this somewhere but no clue if it is relevant

**Comment by chriscoyier** [comment]
I can confirm IE 9 crashing on this particular page. SO WEIRD. I'm open to ideas. It doesn't seem like this page is very different from any other blog post.

**Comment by bkbillma** [comment]
I don't have IE9 anymore but IE10 works (even in IE9 mode).  So not sure if the issue still exists or not

**Comment by chriscoyier** [comment]
I think it is still an issue in IE 9, but I don't know what to do about it. Thanks for checking in IE 10. Gives me even less motivation to figure out the IE 9 issue =)

**Comment by bkbillma** [comment]
Well I can't say with 100% certainty but I bet it is fine in IE9.  With IE10 you can view in IE7/8/9 and it is more than just the user agent.  It completely replicates how the older IE render.  

The only thing I have ever seen it off on was fonts and that was an OS issue not an IE issue (XP didn't support the font used but Win 7 did)

If this helps to motivate you even less then your welcome lol
