### ISSUE TITLE
IE 9 - the comment section of a post - inline form fields are failing.

### ISSUE THREAD

**Issue by megasteve4** [chriscoyier/CSS-Tricks-v10#136]
Just noticed the inline form labels in the comment on post section are blank in IE9...

See here - http://port-80.co.uk/port-80.co.uk/where_have_all_the_lables_gone.png

PS please don't tell anyone I was using IE! (....the shame lol)

**Comment by chriscoyier** [comment]
Uh oh! Will have to fix that.

**Comment by chriscoyier** [comment]
fixed
