### ISSUE TITLE
Lodge Login Position

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#137]
Love the responsive but when on my HTC Titan I have to scroll a lot to get to the lodge login all the way at the bottom.  While the 'sign up now' actually shows up twice before seeing the login.  Not a big issue but seems login should be higher priority than it is.

http://css-tricks.com/lodge

**Comment by chriscoyier** [comment]
Yes that's a good idea...

Probably not much I can do on pages like the Homepage, but for URL's like /lodge/ if you are signed out, I should be able to get the login form a lot higher or at least a jump-down link.

**Comment by bkbillma** [comment]
Yup.  Exactly what I was getting at.  I wouldn't really expect it elsewhere as the /lodge/ is the only place i am going to sign in

**Comment by chriscoyier** [comment]
fix going out today
