### ISSUE TITLE
Forum: unable to add code

### ISSUE THREAD

**Issue by senff** [chriscoyier/CSS-Tricks-v10#138]
Not sure if this is a new feature, or by design, but I'm unable to paste code in the Forum using the old way:

&lt;pre&gt;&lt;code&gt;
CODE GOES HERE
&lt;/pre&gt;&lt;/code&gt;

Gives me a black bar with no actual code in it.

Just using &lt;pre&gt; or just &lt;code&gt; also does not give me proper results.

**Comment by chriscoyier** [comment]
That exact code actually DOES work for me. Can you point me to (or screenshot or screencast) it not working somehow for me? 

For the record, you can also indent code by 4 spaces and it'll pre/code for you (markdown).

**Comment by senff** [comment]
It's happening in this thread/post: http://css-tricks.com/forums/discussion/19444/help-with-button-issue-on-ipad-and-iphone#Item_7

It might actually have to do with the actual code itself. When I just do some dummy text, or when I do the 4 spaces, it works fine. However, it does not work with this code:

&lt;pre&gt;&lt;code&gt;&lt;meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"&gt;&lt;/code&gt;&lt;/pre&gt;

In the example post I've used three different ways of showing the code:
- with writing out &lt; and &gt; as ampersandeltee and ampersandgeetee
- with &lt;pre&gt;&lt;code&gt; and &lt;/code&gt;&lt;/pre&gt;
- with using 4 spaces

**Comment by chriscoyier** [comment]
Just kind of a funny combination of fail here ;)

If you use &lt;pre>&lt;code>, you have to escape the code, cause markdown will ignore it and thus you need to escape it.

If you use the 4-spaces thing, Markdown takes over and then you don't need to escape it because Markdown will do that for you. 

Weird, I know, but I think we should just start using all-Markdown all the time in the forums if possible.

**Comment by senff** [comment]
Doh. Funny combination indeed. Thanks for checking.

Suggestion: add a button that adds markdown to all selected text maybe? A bit like what you had on v9 (selecting text + hitting the button would automatically wrap the text in PRE and CODE).
