### ISSUE TITLE
Shoptalk menu icons in Chrome

### ISSUE THREAD

**Issue by andrewsharp** [chriscoyier/CSS-Tricks-v10#139]
The icons at the top of the shop talk show page are overlapping the words in Chrome (21.0.1180.89 m). running on windows 7 Enterprise.

http://www.freeimagehosting.net/u1nv2  <- Screen shot of icons

**Comment by chriscoyier** [comment]
Cool, we'll get on that. I'm going to close this because this issue list is specifically for CSS-Tricks.
