### ISSUE TITLE
Font icons not working - only letters present...

### ISSUE THREAD

**Issue by shadyyx** [chriscoyier/CSS-Tricks-v10#14]
Hello, I did an easy testing with Firefox 15 and Chrome 21.0.1180.89 m (both on Windows) and here are the first results:

Instead of font icons (that I can see at preview screenshot) I see only random letters, like "k HOME", "9 FORUMS", "Q SNIPPETS", "p GALLERY" etc - in FF 15.

Very strange is this great "ô" letter instead of search icon. Also that search area has cursor like inbetween the text while whole area around has a pointer cursor, but clicking there does holy nothing - clicking on ô without pointer cursor opens the search text box...

In the footer when buzzing around Your icon in the center I can see reflashing anchor links to the left - like there were only 1px height anchor links and I have to hit them precisely... While in Chrome I can see a pretty nice effect there...

The rotated text in Almanac section looks pretty awfull in FF. Compared to Chrome I can see there is also different font used in FF. In Chrome, anyway, after hovering over any anchor link at right side (CSS Properties) within almanac each link gains strange like 1px #eee left border that hangs on and won't disappear.

Demos page - both in FF or Chrome if the content is not large enough to make the box high enough the picture of the demo extends over the box...

I don't like the font used in whole Snippets section...

In FF (and maybe a little also in Chrome) whole css-tricks page behaves kinda laggy...

Wish I could send You the screenshots...

Kind regards
Peter Krajcar.

**Comment by jackweinbender** [comment]
I've observed the same re: the icon font. Strangely, when I'm in the forums section the font seems to work.

**Comment by chriscoyier** [comment]
Font thing fixed.

Demos page clearfix fixed.

Thanks for the feedback / other opinions.
