### ISSUE TITLE
Does the comments section support .md?

### ISSUE THREAD

**Issue by sethburtonhall** [chriscoyier/CSS-Tricks-v10#140]
If so, it is not previewing correctly. Also, the comments preview does not show html.

**Comment by chriscoyier** [comment]
It doesn't yet but it would be nice if it did =)

**Comment by chriscoyier** [comment]
The preview should show HTML. Works for me... http://cl.ly/JQkq

**Comment by sethburtonhall** [comment]
Ok, you I see that is is working for you. I will double check.

+1 for markdown support.

Peace man.

**Comment by chriscoyier** [comment]
markdown in comments is out.

**Comment by sethburtonhall** [comment]
Great, thanks.
