### ISSUE TITLE
¿No https in payment process?

### ISSUE THREAD

**Issue by AlexHackbunker** [chriscoyier/CSS-Tricks-v10#144]
:S

**Comment by chriscoyier** [comment]
VERY temporary. Should be fixed today or tomorrow. HTTPS works but we ran into a nasty error that prevented the page from rendering.

**Comment by AlexHackbunker** [comment]
Great Chris! Then I will subscribe to lodge! ; )

Keep on being the best! Cheers from Spain!

**Comment by chriscoyier** [comment]
Fixed =)

**Comment by AlexHackbunker** [comment]
Gives me an error! Send u a screenshot with the stack

https://www.dropbox.com/s/mufdttkycj5t8fy/payment_error.png

Hope it helps! I can try later! Good luck!

**Comment by chriscoyier** [comment]
Just make sure to be really careful with what you enter for the credit card expiration date. MM for month and YYYY for year. 

This is a known issue I've let the plugin developer know about. Sorry about that! If you get the format correct it should go right through.

**Comment by AlexHackbunker** [comment]
Now it says my username/email already exists! :( Do I have to login and the pay? or u have to delete my account? Sorry asking this way

**Comment by chriscoyier** [comment]
Yep yep, just login first http://css-tricks.com/wp-login.php then go to http://css-tricks.com/lodge/signup/ and it won't ask you about username and all that. Sorry about the hassle.
