### ISSUE TITLE
H3 background is covering article content

### ISSUE THREAD

**Issue by KustomDeveloper** [chriscoyier/CSS-Tricks-v10#145]
Look at this article here: http://css-tricks.com/pseudo-element-roundup/

For whatever reason you set  .one-thing h3  to -38 margin on the bottom and it is now covering some of the content. I'm guessing that since it is named .one-thing that you only did it once. Setting the margin to 20px seems to fix it. 

viewed in newest Chrome version...whatever that is... on Win 7 OS....cheers:)

**Comment by chriscoyier** [comment]
Just how that article is designed. Looks like shit, I'm aware, but I did that on purpose for some reason =/. Have a note to redo that article soon.

**Comment by KustomDeveloper** [comment]
Okay, I just wanted let you know it was there.
