### ISSUE TITLE
[Forums] No more [Solved] mention

### ISSUE THREAD

**Issue by KittyGiraudel** [chriscoyier/CSS-Tricks-v10#146]
On the topic list, I can't see any [Solved] mention, even if plenty of them are tagged as solved. When I get into a topic however, the [Solved] mention is displayed before the title.

Chrome 21, Windows XP.

**Comment by chrisburton** [comment]
I don't have this issue in Chrome on W7

**Comment by chriscoyier** [comment]
Seems to be working for me too: http://cl.ly/JXdA

**Comment by KittyGiraudel** [comment]
Indeed. It works when you're watching "All discussions". However, it doesn't seem to behave properly when you're in a category.

See : http://i.imgur.com/7wyEU.jpg

**Comment by chrisburton** [comment]
Now I see it. I have that issue as well.

**Comment by KittyGiraudel** [comment]
Still no patch for it Chris? :(

**Comment by chriscoyier** [comment]
It uses the exact same view, so it's weird it doesn't show up. 

In the plugin itself that adds this functionality, it looks like it just skips this view.

```
   /**
    * Add prefix to discussion name in single discussion view (vanilla/controllers/class.discussioncontroller.php)
    */
   public function DiscussionController_BeforeDiscussionRender_Handler(&$Sender) {
      if($Sender->Discussion->Prefixed == 1)
         $Sender->Discussion->Name = C('Plugins.DiscussionPrefix.Prefix').' '.$Sender->Discussion->Name;
   }

   /**
    * Add prefix to each discussion name in list view
    */
   public function DiscussionsController_BeforeDiscussionName_Handler(&$Sender) {
      if($Sender->EventArguments['Discussion']->Prefixed == 1)
         $Sender->EventArguments['Discussion']->Name = C('Plugins.DiscussionPrefix.Prefix').' '.$Sender->EventArguments['Discussion']->Name;
   }
```

I don't know enough about Vanilla internals to fix it.
