### ISSUE TITLE
Icon fonts not working 

### ISSUE THREAD

**Issue by Luxbit** [chriscoyier/CSS-Tricks-v10#148]
Hey, I just wanted to let you know that iconfonts do not work in opera mobile.

**Comment by chriscoyier** [comment]
Can you list the specific device and version and anything else you know? Opera Mobile on a galaxy tab seems to load them OK: http://cl.ly/JUCW  (plenty of other problems though)

**Comment by Luxbit** [comment]
I noticed the problem on my iPad 3 using the latest version of Opera Mini Version 7.0.3.40701
