### ISSUE TITLE
"Download Video File" On Video List Page Opens Video

### ISSUE THREAD

**Issue by CWSpear** [chriscoyier/CSS-Tricks-v10#150]
On http://css-tricks.com/lodge/v10/, when I click "Download Video File" button, the video opens in the window full screen (i.e. it doesn't download).

I noticed the only different between the download buttons between the video list page and the individual video page is the download attribute on the anchor tag. Via the Chrome inspector, **I added a blank download attribute to the download anchor and it worked as expected.**

I didn't know there was a download attribute.

I'm using Chrome 21.0.1180.89 on Mac OSX 10.8.1

**Comment by bkbillma** [comment]
Does the same on my FF.  I've just used IE to dl it and didn't bother reporting

**Comment by chriscoyier** [comment]
download attribute added in list view

yah it's pretty neat, you can even control the file name it suggets if you have it open the file download dialog instead of direct download
