### ISSUE TITLE
font size much too small on Android phone

### ISSUE THREAD

**Issue by pdewouters** [chriscoyier/CSS-Tricks-v10#154]
the font size is too small and makes it difficult to read the content on my Samsung Galaxy Y android phone.

**Comment by chriscoyier** [comment]
Hey Paul do you have another camera you can snap a picture of the phone with an article open on?

**Comment by chriscoyier** [comment]
Made some adjustments here. Going to close for now unless it's still a problem and we can get a picture.

**Comment by pdewouters** [comment]
thanks Chris, it's much better
