### ISSUE TITLE
Forum: Code comments are whack

### ISSUE THREAD

**Issue by graygilmore** [chriscoyier/CSS-Tricks-v10#156]
Comments in code are covering other bits of code: http://cl.ly/image/071A0c150v1q

**Comment by chriscoyier** [comment]
I feel like I've seen that before but now I'm trying to replicate it and can't seem to. Can you post here exactly the comment text you are using to get it to render that way?

**Comment by graygilmore** [comment]
http://css-tricks.com/forums/discussion/19471/apply-class-to-parent-if-child-div-contains-class#Item_25

This is where I've most recently seen it. I'm looking in Chrome Canary, which could be the problem.

**Comment by chriscoyier** [comment]
got it, fix going out for this.
