### ISSUE TITLE
Remove WP bar for logged in lodge members - not really needed.

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/CSS-Tricks-v10#159]
Maybe replace with something else that is more useful and lodge-specific?

**Comment by joshbetz** [comment]
I like the idea of removing. The `show_admin_bar()` function is probably the easiest way to remove it.

``` php
add_action( 'init', function() {
    if ( ! current_user_can( 'edit_posts' ) )
        show_admin_bar( false );
});
```

**Comment by chriscoyier** [comment]
baller. I got it in there. Unfortunately it still injects the CSS to make room for the bar...

So ultimately I did:

```
  add_action('init', 'csstricks_hide_admin_bar');
  function csstricks_hide_admin_bar() {
    if (!current_user_can('edit_posts')) {
      show_admin_bar(false);
      add_action('wp_head', 'csstricks_remove_space');
    }
  }
  function csstricks_remove_space() {
    echo '<style>html { margin: 0 !important; }</style>';
  }
```

It would be nicer to just not inject the styles that adds the margin to begin with...

**Comment by joshbetz** [comment]
Ohh... I guess `init` is one action too late. If you do it on `set_current_user` instead, the CSS doesn't get injected.

``` php
add_action( 'set_current_user', function() {
    if ( ! current_user_can( 'edit_posts' ) )
        show_admin_bar( false );
});
```

**Comment by chriscoyier** [comment]
oooh nice. yur smart
