### ISSUE TITLE
Treehouse ad at top links to #

### ISSUE THREAD

**Issue by ajmarino** [chriscoyier/CSS-Tricks-v10#16]
The tree house ad space at the top of the page is still using a placeholder href attribute: '#'.  Not too sure if this is intentional so the click event is handled through javascript, or just a slight overstep in the rush to launch the site.  Nothing big, but needs to be updated if you want those referral links :).

**Comment by caycefischer** [comment]
Was just going to submit this. ++

**Comment by macbookandrew** [comment]
@zakkain same here :)

**Comment by KittyGiraudel** [comment]
Same here too.

**Comment by chriscoyier** [comment]
OOPS.

Fixing going up now. Thanks folks!
