### ISSUE TITLE
Forum: PHP tags causing code to be stripped

### ISSUE THREAD

**Issue by graygilmore** [chriscoyier/CSS-Tricks-v10#160]
Including opening and closing PHP tags would cause a bunch of the code to be stripped from forum posts.

I've created a test post for ya:

http://css-tricks.com/forums/discussion/19620/just-testing-dont-mind-me

**Comment by chriscoyier** [comment]
Weird. Looks OK? http://cl.ly/JcC2

**Comment by graygilmore** [comment]
So weird. I tested in multiple browsers and saw it. Fire it up this morning, cleared some caches, looks fine.

**Comment by chriscoyier** [comment]
I think it was some dumb script change I made.
