### ISSUE TITLE
Comment Preview has more markdown than actual Comment

### ISSUE THREAD

**Issue by CWSpear** [chriscoyier/CSS-Tricks-v10#161]
I tried using back ticks to do inline code (I believe it is "github flavored markdown," but it showed up in the preview, so I used it, but when I submitted my post, it went back to just normal back-ticks.

For example, see how I authored `_bits.scss` and how it showed up in the preview: http://cl.ly/image/1m3I3S0p1r01

And compare that to how it showed up in the comment thread:  http://cl.ly/image/2L1t1o3n2U24

**Comment by chriscoyier** [comment]
Temporary issue, fixed =)
