### ISSUE TITLE
Change color on viewed videos, blog posts, etc.... use of css a:visited

### ISSUE THREAD

**Issue by pfortes** [chriscoyier/CSS-Tricks-v10#164]
Hey there Chris,

I dont know what was the reason for having the same color on the links that have been visited than the ones that haven't

I think this is a major usability flaw, as i cant know which videos i have watched in the lodge  and what blog posts i have read already...

Maybe changing the links to be a lighter gray when they have been visited could help knowing whats visited without changing to much the site design!

Hope to hear your comments on this

and great work!

tnx

**Comment by chriscoyier** [comment]
Added a "mark as watched" feature =)
