### ISSUE TITLE
Problem with the opensearch settings

### ISSUE THREAD

**Issue by webbushka** [chriscoyier/CSS-Tricks-v10#165]
There is an issue with your opensearch, the xml looks right but there is a problem when actually using the feature in Chrome. If you use the site search that is built into your site the URL works and looks like this:

http://css-tricks.com/search-results/?q=nth-child

if you use opensearch through Chrome's URL bar the resulting search URL is:

http://css-tricks.com/?s=nth-child

if you hit that URL the site is extremely broken.

**Comment by chriscoyier** [comment]
Should be fixed.
