### ISSUE TITLE
Subscribing to comments doesn't email me when someone else comments.

### ISSUE THREAD

**Issue by CWSpear** [chriscoyier/CSS-Tricks-v10#166]
I've double checked that I am indeed subscribed to comment threads. I've done it before and it's worked, but it hasn't worked in v10. People have even responded to my comments and I didn't get a notification email (I double checked my spam).

I have only subscribed to comments in the Lodge section, so is it possibly related to that?

**Comment by chriscoyier** [comment]
I bet it is specific to the lodge. Those pages are protected behind the login wall, so I bet WordPress.com (i.e. JetPack and the subscription sending service) can't really see what's going on there and can't send the reply emails.  

I'll see what I can do there. If nothing else, just remove the buttons (somehow) for lodge comment threads.

**Comment by chriscoyier** [comment]
solving this by removing those subscription buttons while in the lodge. Not 100% ideal but nature of the beast for members-only areas. Subscribing to new posts is weird anyway, and might make people believe they will get emails when new lodge content is posted.
