### ISSUE TITLE
In Opera 12 : white spaces in main nav, treehouse header font, small width main nav height

### ISSUE THREAD

**Issue by guimouzo** [chriscoyier/CSS-Tricks-v10#167]
Hello,

I saw three small problems testing the website in Opera 12 on Mac os 10.6 :
- it adds a pixel between `<a>` tags in the main nav, because of the lines break in the html code ?
- on hover, the Treehouse ad's webfont in the header is not working. But it may come from a font problem on my computer…

Screenshot : http://imgur.com/a/XDhZb#0
- in small width window, closed main nav is as high as the page wrap

Screenshot : http://imgur.com/a/XDhZb#1

(I don't have this problems in other browser)

**Comment by chriscoyier** [comment]
I confirmed the navigation bug and fixed it. Couldn't confirm the others - seems a bit isolated. Thanks for the report though, will keep eye out.
