### ISSUE TITLE
Videos out of order

### ISSUE THREAD

**Issue by kyled** [chriscoyier/CSS-Tricks-v10#17]
Starting on [Delta](http://css-tricks.com/video-screencasts/page/4/) the order of the videos messes up.  #28 follows #44, and #24 follows #28, and then the next three pages of videos are out of order.

**Comment by KittyGiraudel** [comment]
Same here. Looks fine before Delta.

**Comment by chriscoyier** [comment]
Yes!

I have a plan for this.

**Comment by chriscoyier** [comment]
Fixed.
