### ISSUE TITLE
Report bug button doesn't work

### ISSUE THREAD

**Issue by alanmoo** [chriscoyier/CSS-Tricks-v10#170]
This wasn't what I came to submit, but it looks like there's some javascript disabling the default event on your "Report Issue" button on http://css-tricks.com/design-v10/

**Comment by chriscoyier** [comment]
Weird. Can't replicate. Lemme know if you have more specifics on how to reproduce.

**Comment by alanmoo** [comment]
Huh. Not happening to me today either. Definitely seemed JS related as the button worked when I turned JS off, but not when it was on. Weird.
