### ISSUE TITLE
Bring back the 'Mark All Read' button in the forums.

### ISSUE THREAD

**Issue by joshnh** [chriscoyier/CSS-Tricks-v10#172]
This goes hand in hand with making the 'New Comment' indicator much more visible. Don't be afraid to use a bit of contrast!

**Comment by chriscoyier** [comment]
Should be set.

**Comment by joshnh** [comment]
Chris, the button is now present, but it is doing absolutely nothing at all for me.

**Comment by chriscoyier** [comment]
Blah. Me too. Will have to investigate again.

**Comment by chriscoyier** [comment]
I spent several hours on this today.

https://gist.github.com/3873256

Line 77.

That function never runs and that's the core of what makes this work. Everything else in there I can get to run. The note it has about requiring some code in DiscussionModel->Get() is there. 

I have no idea why it never gets called.

**Comment by chriscoyier** [comment]
Alright now it works

hahahahha

{{ CRIES }}
