### ISSUE TITLE
IE10 Metro Snap

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#175]
As annoying as it is that MS requires special code for the snap, could you add it in for CSS-Tricks?  I love easily having a site snapped to the side and easy to read.  http://blogs.msdn.com/b/ie/archive/2012/06/19/adapting-your-site-to-different-window-sizes.aspx

Thanks

**Comment by chriscoyier** [comment]
pushing now, thanks
