### ISSUE TITLE
After hovering main nav blocks' right-shadows become solid

### ISSUE THREAD

**Issue by amaisano** [chriscoyier/CSS-Tricks-v10#176]
What I'm seeing (image): http://client.clevelanddesign.com/CD/css-tricks-menu-glitch.jpg

What I'm using: Safari 5.1.7 (6534.57.2) on OS X 10.6.8

How I did it:

1) Visit the home page, size the browser so that the main nav is all inline

2) Hover over any of the links (except for the last two). Right-side shadow becomes solid bar.

3) Un-hover / move the mouse away. The solid bar sticks until the browser is resized.

**Comment by amaisano** [comment]
Hovering on the menu item to the right of the item with the glitched right-shadow also clears the problem, returning it to the gradated shadow.

**Comment by chriscoyier** [comment]
Thanks for the comprehensive report! I wish there was a simple fix but I can't think of anything. The bug isn't present in 10.8 and Safari 6 and trying to do sub-version of Safari fixes sounds pretty nightmareish to me. I think we might just press forward to the future on this one.

**Comment by amaisano** [comment]
Weird, I wonder what low-level differences between the versions is causing this kind of glitch. Must be a core rendering thing. Thanks for the reply, and great job on the redesign!
