### ISSUE TITLE
.gsc-result .gs-title not tall enough

### ISSUE THREAD

**Issue by korkey128k** [chriscoyier/CSS-Tricks-v10#177]
Looks like `.gsc-result .gs-title` height is at `1.2em` not leaving enough room for the text.  
Bumping it up to `1.3em` does the trick for me.  

Tested on Chrome 22.0.1229.94, Firefox 15.0.1, Opera 12.02.

Also, on Opera, theres some Font FOUT happening, if you didn't know.

**Comment by chriscoyier** [comment]
This is what I'm getting pretty consistently cross browser: http://cl.ly/KW5J

It's kind of weird that it has a height at all though... I might just strip that out.
