### ISSUE TITLE
FORUMS - "Code" button not functioning properly

### ISSUE THREAD

**Issue by KennyGScott** [chriscoyier/CSS-Tricks-v10#178]
In v9 pressing the code button would output the pre & code tags to the textarea...Upon pressing the code button, it seems to render the html in the textarea rather than print to it...I am using Chrome/Windows 7

**Comment by chriscoyier** [comment]
I updated it a bit -- now it indents the code block -- which is what is required in Markdown to be a code block (essentially wraps pre and code blocks)
