### ISSUE TITLE
IE .explanation on non-block element

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#179]
when you put the .explanation class on the <em> tag for the post '5 Use Cases For Icon Font' it looks pretty wonky.  

In web dev tools I added display:block and it works fine.

![css-tricks-ie-display-block-issue](https://f.cloud.github.com/assets/1844184/34064/01fbaad4-50f4-11e2-9593-717d75cb8a9b.png)

**Comment by chriscoyier** [comment]
That was just a temporary thing until the cache was flushed. Display: block was on there. I did it this way so the intro paragraph would be in italics over RSS =)
