### ISSUE TITLE
Nav Issue at about 960px

### ISSUE THREAD

**Issue by GaneshaIX** [chriscoyier/CSS-Tricks-v10#18]
When resizing the browser on CSS-Tricks, at around 960px the nav either shrinks or completely disappears. A screenshot was sent to Chris Coyier on Twitter by @GaneshaIX to show what it looks like.

**Comment by chriscoyier** [comment]
Not seeing this issue at the moment. It might be fixed. Otherwise repopen with a screenshot and browser details. Thank you!

**Comment by GaneshaIX** [comment]
I took a screenshot of a comparison with the browser windows at the approximate width for that media query to take effect. LTR is Aurora 17.0a2, Opera 12.0, Chrome 21.0.1180.89, Maxthon 3.4.2.3000, and IE 9.0.8112.16241

http://imgur.com/OBFIG

The browser that caused me to open this issue is Aurora, because as you can see, "Navigation 'N' Search"is just not there.

I hope this helps!

Operating System is Windows 7 Home Premium

**Comment by chriscoyier** [comment]
Made some positioning changes to this button, should be showing up.
