### ISSUE TITLE
Tags, 'Likes', Popularity Filters on Snippets

### ISSUE THREAD

**Issue by bkbillma** [chriscoyier/CSS-Tricks-v10#180]
Not an issue per se but I feel the snippets could be more useful with things like this.  Tags could help for someone looking for something specific.  Likes and/or view based could just help people to explore newer hot topics.  

And perhaps even a way to view by comments (or that could be the most popular ones)

Just spitballing thanks for all the great work

**Comment by chriscoyier** [comment]
Good idea! 

I'd really like to do more stuff like this. Get the forums on the WordPress side as well. That way everyone who interacts with CSS-Tricks can have an account and do all this fancy stuff (like "like" a snippet to remember it).

**Comment by chriscoyier** [comment]
Gonna have to say next redesign on this one, when the goal will be bringing the entire site more together socially. e.g. bring forums into bbpress, wiki-ize bits, etc.
