### ISSUE TITLE
Comment parser messed up (+ Markdown doesn't work)

### ISSUE THREAD

**Issue by Krinkle** [chriscoyier/CSS-Tricks-v10#181]
- Single quotes and double quotes are sometimes (but not always?) converted to backticks and curly quotes (thus invalidating program code, and generally annoying).
- ... as a result we have to use `&quot;` or `&#039;` to keep it cool.
- Markdown syntax for **bold**, _italics_, [link](http://example.org), `inline code` and code blocks (3 backticks) do not work.
- ...as a result we have to resort to `<code>` and `<pre>`, which means manual html escaping, which is dull.
- Leading spaces of any kind are ignored, `&nbsp;` is required to make indentation work.
- .. except for the first line. There must be no space between `<pre><code>` and the start of the code, as a line break there would be rendered.
- Unclear why `<code>` is used inside `<pre>`. It appears to only add padding?

Example at css-tricks:
![CSS-Tricks WordPress comment example](https://s3.amazonaws.com/f.cl.ly/items/311c002S1n093j3m0T0c/csstricks-comment-ugly2.png)

Example at GitHub:
![GitHub comment example](https://s3.amazonaws.com/f.cl.ly/items/1i2H0T1y0g0m1w0g1o3a/csstricks-comment-mess.png)

**Comment by chriscoyier** [comment]
fixed mostly... triple backticks is a github thing that I'd like to add but can't do myself.
