### ISSUE TITLE
Focus when logging into forums

### ISSUE THREAD

**Issue by KittyGiraudel** [chriscoyier/CSS-Tricks-v10#183]
Clicking on "Sign in" in the forums section opens some kind of pop-up asking for name/email and password. The fact is there is no focus on the first field and pressing tab is moving the focus on the page behind the lightbox (the main logo, then the nav, etc.).

Any chance you'd put some kind of autofocus or tabindex to the email field in order to be able to login without having to use the mouse?

Thanks Chris. :)

**Comment by chriscoyier** [comment]
Good idea. Will get to when I can.

**Comment by chriscoyier** [comment]
fix is going out for this today

**Comment by KittyGiraudel** [comment]
Terrific Chris, thanks a lot. :)
