### ISSUE TITLE
need ICO for favicon instead of PNG

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/CSS-Tricks-v10#184]
For IE

**Comment by bkbillma** [comment]
Silly IE.  While you are at it could you set you site up for IE9 and 10 pinning.

http://www.buildmypinnedsite.com/

http://www.buildmypinnedsite.com/windows7/en

**Comment by chriscoyier** [comment]
fixed. Gonna pass on pinning until I get my hands on a windows tablet for testing.
