### ISSUE TITLE
URL for demos page

### ISSUE THREAD

**Issue by dclardy64** [chriscoyier/CSS-Tricks-v10#187]
This is just a request for you to put a .htaccess redirect for http://css-tricks/demos to go to the downloads page. The menu name is a little deceiving. It seems like it is something that could be easily added.

The reason that I am requesting is because I just tried to go to that page, and I got your 404 page. Other people might be doing the same thing.

**Comment by chriscoyier** [comment]
Sorry for the delay on this. I was about to write a bit of .htaccess whatever to do it and I felt weird about it. I'm not confident enough that it wouldn't harm past or future articles with a slug that might start with demos\* . And the problem that it would solve is someone essentially URL hacking that page, as there aren't and links in the wild to /demos I don't think. If you tried and and got the wrong place, I imagine the next course of action is go to the homepage and find the nav link you meant, which ain't so bad I don't think.

**Comment by dclardy64** [comment]
Yeah. I just got use to it being called demos. So I typed in to the address bar, http://css-tricks.com/demos. This of course give you a 404. I knew that was not right so I went back and figured it out.
