### ISSUE TITLE
z-index issue with search error message and main navigation

### ISSUE THREAD

**Issue by neilcarpenter** [chriscoyier/CSS-Tricks-v10#19]
Error messages when using site search, eg. just searching without entering any text in the input, and receiving "Please fill out this field", are semi-hidden underneath the main navigation. Viewing at about 1600px wide.

**Comment by chriscoyier** [comment]
Ah yeah it's the overflow hidden that's causing it, not z-index. I put that "required" attribute in there at request by a user. I wonder if I should remove it. Or... maybe disable the search input until text is present in the field. Any opinions?

**Comment by neilcarpenter** [comment]
Hmm would be a pretty good use-case for overflow-x and overflow-y! 

You could put a `setTimeout` on the search click event to add a class which enables `overflow: visible` once the transition has completed (or use `transitionEnd`), but feels a bit 'hack-y', and perhaps overkill. 

Could disable search until text is present, which would be pretty much the same as is now, without the error message, which could _potentially_ be confusing for user. Or I personally think it would be fine just remove the required attribute. 

Either way I think your suggestions are probably better than a half-visible tooltip...

**Comment by chriscoyier** [comment]
Good ideas! I tried overflow-x/y but unfortunately there is some wonkyness there. They both needed to be hidden for various reasons. I'm just removing required for now.
