### ISSUE TITLE
Forum Log In not working on iOS Chrome

### ISSUE THREAD

**Issue by noelforte** [chriscoyier/CSS-Tricks-v10#194]
I'm using Chrome on iOS (iPod Touch), and I can't seem to log in to the forums. It doesn't matter if "Remember me" is checked, the end result is simply redirecting the user back to `http://css-tricks.com/forums/` without logging them in.

Not sure if this behavior is also mirrored on iPhones/iPads, or Android.

**Comment by chriscoyier** [comment]
I'm on the case! I think it's a browser cache thing which I've removed as a test. I also have some other smart folks working with me on this because it's definitely an issue.
