### ISSUE TITLE
Saw few padding issues in Chrome for Android

### ISSUE THREAD

**Issue by sandeshdamkondwar** [chriscoyier/CSS-Tricks-v10#196]
Your site is the one of the best example for responsive design.
Saw few glitches with padding in comments section. 

![screenshot_2014-05-11-19-02-04](https://cloud.githubusercontent.com/assets/2510560/2938533/b2bdc446-d911-11e3-80b5-ac13be005d14.png)

**Comment by chriscoyier** [comment]
The headers are supposed to touch like that. It's a design element. But a zillion people have done this exact thing and warned me that it's a bug that it's probably worth changing. Maybe someday.
