### ISSUE TITLE
SVG line animation do not work under Microsoft Edge

### ISSUE THREAD

**Issue by Syndesi** [chriscoyier/CSS-Tricks-v10#198]
Hello chriscoyier,

your tutorial ( https://css-tricks.com/svg-line-animation-works/ ) do not work under Microsoft Edge.
I found out that the JS still works, but the CSS not.
I hope that you can find a solution.

Have a nice day, Sören Klein.

**Comment by ghost** [comment]
MS Edge does not support (apparently) styling SVGs with CSS3. Found this the hard way. If anyone could explain why is that so, or is there a workaround solution, please do share :)

**Comment by Syndesi** [comment]
So, there seems to be an alternative: [vivus.js](https://maxwellito.github.io/vivus/).
With this library it's possible to render line animations on Edge and I think it's possible because they don't use CSS at all, but I could be wrong.
Either way, it works :D
