### ISSUE TITLE
Poll display blank after poll submitted

### ISSUE THREAD

**Issue by FriendlyWP** [chriscoyier/CSS-Tricks-v10#23]
After answering the 'do you listen to music' poll, the poll box becomes blank, just the background shows.

If it matters, this happened on Windows 7 in Chrome 21.0.1180.89 m. 

Love the new design! :)

**Comment by ericski** [comment]
Same problem with OSX 10.8.1 in Chrome 21.0.1180.89 and Firefox 15.0 (results do appear after a refresh)

**Comment by maxdmyers** [comment]
+1 (OS X 10.8.1 and Chrome 21.0.1180.89)

**Comment by chriscoyier** [comment]
Poll fixed! It was an issue with me trying to force HTTPS on wp-admin.
