### ISSUE TITLE
Asterisk in title is missing

### ISSUE THREAD

**Issue by svivian** [chriscoyier/CSS-Tricks-v10#24]
The historic text is still at the bottom of the page:

> \* This site may or may not contain any "CSS" or "Tricks".

But there is no asterisk that refers to said text. Previously it was after "CSS-TRICKS" in the title/logo. Maybe you decided not to bother with it but thought I'd mention it in case you forgot :D

**Comment by chriscoyier** [comment]
Thanks! Yeah I'm leaving the asterisk out of the header. There is a big one in the footer now (at large screen sizes anyway) =)
