### ISSUE TITLE
strange word truncation

### ISSUE THREAD

**Issue by flumpies** [chriscoyier/CSS-Tricks-v10#25]
i am sure you have a lot of comments on this: but your text is getting "hyphenated" in weird spots (like 'wo" and then 'ord')

**Comment by senff** [comment]
Example can be found here: http://css-tricks.com/forums/discussion/comment/76426/#Comment_76426 (only giving this exact example because that's where I noticed it myself)

Chrome/Safari looks fine, but words are being cut off differently between various browsers.

**Comment by jtojnar** [comment]
Duplicate of #9

**Comment by chriscoyier** [comment]
Ya'll were in Firefox right? It was pretty bad on some platforms. Pushed up a fix. Re-open this if it's not fixed.
