### ISSUE TITLE
Search validation tooltip hidden behind navbar in Chrome

### ISSUE THREAD

**Issue by ghost** [chriscoyier/CSS-Tricks-v10#26]
With the search expanded, submitting the form with the input field empty brings up and validation tooltip. In Chrome the tooltip appears behind the navbar and is unreadable.

The tooltip appears properly in the z-index in the latest FF nightly but the icon does not appear.

In Safari, there seems to be no validation at all. Submitting with an empty field still submits.

**Comment by chriscoyier** [comment]
fixed. just not showing that message anymore.
