### ISSUE TITLE
Posting message on forum: doesn't show until page refresh

### ISSUE THREAD

**Issue by senff** [chriscoyier/CSS-Tricks-v10#32]
When posting a message on the forum, the form will go blank after hitting the SUBMIT button but the message doesn't actually appear at the bottom of the thread. You'll have to do a full page refresh in order to see it appear.

**Comment by KittyGiraudel** [comment]
Same here. Noticed it twice.

**Comment by cshawaus** [comment]
Can also confirm this happens but no error occurs

**Comment by chriscoyier** [comment]
Yeah this one really sucks. I bet it's an easy fix though once I track it down. I bet it has to do with markup/ID's and something not being there when Vanilla tried to inject the new post after submission.

I wish an error would trigger...

**Comment by KittyGiraudel** [comment]
Just posted something on the forum, the page showed it correctly without having to refresh. Problem solved ?

**Comment by chriscoyier** [comment]
Yeah I worked on it this morning and think I got it.
