### ISSUE TITLE
Jerkyness when scrolling

### ISSUE THREAD

**Issue by BeingTomGreen** [chriscoyier/CSS-Tricks-v10#33]
I seem to be getting a lot of jerkyness/juddering when scrolling up and down, only seems to affect Chrome though..

Looks amazing btw.

**Comment by chriscoyier** [comment]
I have this issue just a litttttle bit too. I wonder if there are some fancy hacks I could put in to fix...

**Comment by BeingTomGreen** [comment]
I am sure there must be something you could do, but I am not really sure what. You are the front end expert :)

I really is beautiful though!

**Comment by chriscoyier** [comment]
Removed a few box-shadows and scrolling is nicer now it seems. Lemme know if you feel an improvement or not.

**Comment by BeingTomGreen** [comment]
Seems much better now!
