### ISSUE TITLE
snippets tab-persistance 

### ISSUE THREAD

**Issue by jcsrb** [chriscoyier/CSS-Tricks-v10#34]
_Scenario:_
1. looking for .htaccess snippets 
2. click on one to open
3. go back to see more htaccess goodness

_expected_
see more .htaccess snippets

_actual_
site shows html snippets

**Comment by chriscoyier** [comment]
Yeah I could see that being cool... If you back up only one level to http://css-tricks.com/snippets/htaccess/ it does persist, but if you press the back button in your browser it doesn't. I guess I could use localstorage or something...

**Comment by chriscoyier** [comment]
This is going out now and works in any browser with localStorage
