### ISSUE TITLE
Forum: Inline Markdown Creates New Paragraph

### ISSUE THREAD

**Issue by graygilmore** [chriscoyier/CSS-Tricks-v10#35]
Sample forum post:

"Hey, isn't it cool how you can use `markdown` now!?"

Here, on github, that looks all nice on one line, but the output in the forum will be:

"Hey, isn't it cool how you can use `markdown`
now!?"

Everything after the `<code>` tag is being wrapped in a new `<p>` tag: http://cl.ly/image/2p0B1N0W2o12

**Comment by KittyGiraudel** [comment]
Agreed, happened to me too.

**Comment by chriscoyier** [comment]
Miiiight be fixed. I turned off a plugin that may have been conflickting.

**Comment by graygilmore** [comment]
Yup, looks good to me.
