### ISSUE TITLE
Edit Profile Issues

### ISSUE THREAD

**Issue by huwrowlands** [chriscoyier/CSS-Tricks-v10#36]
Once I log in and click on the Edit Profile link (right hand sidebar), I get taken to wp-login.php which asks me to log in again. 
I log in, again, and try the same thing, and get redirected to wp-login.php once again.

Not sure why that's happening?!

**Comment by eduard-un** [comment]
Same here using Firefox 15 and Chrome 21.0.1180.89. the odd thing in here is that in Safari it works to edit your profile! Maybe Chris knows better!

**Comment by chriscoyier** [comment]
I made some changes to how login stuff works... hopefully it's better now. Reopen this if you keep having the problem after a cache/cookie flush. And if you possibly can screencast it happening that would be awesome.
