### ISSUE TITLE
Name / email issue on comment

### ISSUE THREAD

**Issue by KittyGiraudel** [chriscoyier/CSS-Tricks-v10#38]
Posted a comment on the last blog post a few minutes ago, it displayed my email instead of my name, with no link to my website.

http://css-tricks.com/design-v10/#comment-189827

Weird bug.

**Comment by chriscoyier** [comment]
Yeah this is a sucky problem. I fixed your comment. The deal is, you have to go here: http://css-tricks.com/wp-admin/profile.php and update your display name so when you comment it doesn't use your username.
