### ISSUE TITLE
Forum: clicking on thread does not take you to last unread post

### ISSUE THREAD

**Issue by senff** [chriscoyier/CSS-Tricks-v10#40]
I believe that on the previous version of the forum, clicking on a thread would take you directly to the last unread post. Now, when visiting a thread, it just always goes to the top post.

**Comment by chriscoyier** [comment]
Yeahhhhh I know what you mean. Hm. But there is no hash link in the URL that would do the jump down is there?

**Comment by senff** [comment]
Actually, there is a hash in the link (that's definitely related to the last unread post!), but it just doesn't go anywhere. 
Example: http://css-tricks.com/forums/discussion/18372/best-free-css-editor#Item_11 will just lead to the top of the thread, since the lisitems don't have that ID with "Item_xx", just "Comment_xxxxx".

**Comment by chriscoyier** [comment]
That's very good news, just means I'm screwing up ID's in the templates somewhere. If I can fix, might fix a few other issues too...

**Comment by chriscoyier** [comment]
I thinkkkkk I got this fixed.

**Comment by senff** [comment]
Looks like it! Thanks much

Not sure if it should also always jump to the latest message if all message are read (I prefer it to start at the bottom) but that's probably personal.
