### ISSUE TITLE
Font icons not working in FF on Mac

### ISSUE THREAD

**Issue by weslers** [chriscoyier/CSS-Tricks-v10#42]
Congrates on the redesign Chris. While viewing the site on FF 12.0 the font icons on the menu are appearing. So k is appearing before home, 9 is appearing before forums etc.

See screen shot here http://goo.gl/EC8wF

**Comment by lo5an** [comment]
I'm seeing the same thing in FF 16 beta

**Comment by nhoizey** [comment]
+1 with FF15 on Mac OS X Mountain Lion

**Comment by sebastiandedeyne** [comment]
FF 15 on Lion having trouble too

**Comment by chriscoyier** [comment]
Deploying another fix. Somehow my magical htaccess fix didn't hold.
