### ISSUE TITLE
Long, non-breaking, text in comments causes horizontal scrollbar on small width devices.

### ISSUE THREAD

**Issue by ryanswedal** [chriscoyier/CSS-Tricks-v10#46]
If someone posts long text without breaks for their comment (eg. the title of this comment... http://css-tricks.com/design-v10/#comment-189879) then a horizontal scrollbar will appear on small width devices.

**Comment by chriscoyier** [comment]
I had a fix for this (word-break), but it was causing other issues. I think I'll just hide overflow on the entire comment wrapper, that should prevent it.
