### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by lucasBel** [chriscoyier/CSS-Tricks-v10#5]
First, it'S a georgous design! congrats, the first issue that i see is the font, it look verry weird not clean at alll, on chrome on windows xp. The font look without any anti-alias at all.

**Comment by danielcha** [comment]
As far as I know this is an issue with Chrome on Windows... I'm also having this problem with my own redesign project. The webfonts are crisp in IE9 and FF. And in Chrome on the Mac...

On Windows 7 in Chrome this page is nearly unreadable: http://css-tricks.com/snippets/

**Comment by jdecock** [comment]
They look bad in FF 15.0 on Windows as well.

**Comment by chriscoyier** [comment]
Most fonts have been updated and more updates to come. Sometimes fonts on windows just look like shit, which is very sad but I expect it to improve over time. If this continues to be a really bad problem, I might just take drastic measures and do some platform sniffing and stop serving custom fonts to windows all together. Thanks for the feedback folks, it's frustrating territory.
