### ISSUE TITLE
Comment preview - blinks gravatar too frequently when typing...

### ISSUE THREAD

**Issue by megasteve4** [chriscoyier/CSS-Tricks-v10#51]
I'm guessing this there is a key up event to update the comment preview when you type....  But in Chrome at least as I type frequently my gravatar vanishes from the preview pane meaning the comment text jumps to the left then when the gravatar reappears the text is pushed right again...  Making for quite a jerky experience.   

I am guessing but might suggest only changing the gravatar in the preview pane if the email address is updated not on every key up....

But as already mentioned - loving the new look...

**Comment by chriscoyier** [comment]
I think this may have been improved/fixed. I was able to replicate it at one time but now cannot. 

Thanks for the report!
