### ISSUE TITLE
Contrast issue for secondary information

### ISSUE THREAD

**Issue by joshnh** [chriscoyier/CSS-Tricks-v10#52]
In various places throughout the site, for secondary information, there is a text colour of #D6D5D5 being used on a white background. This is incredibly hard to read, and I have no issues with my eyes.

**Comment by chriscoyier** [comment]
I may darken that up a touch. I like how it's way subdued though. It's usually the time element and not something that needs much attention called to it.

**Comment by joshnh** [comment]
That sounds fine, however it doesn't really fly from an accessibility point of view. Subdued to you may very well be invisible to others. Perhaps darkening on hover is a potential solution?
