### ISSUE TITLE
Design Consistency

### ISSUE THREAD

**Issue by chrisjaure** [chriscoyier/CSS-Tricks-v10#54]
I like how each section of the site has a different design, however, I think it changes too drastically. The layouts, pagination, etc., are not consistent. And what's up with the almanac? Perhaps if the outer area were a little more branded, each section wouldn't look like an entirely separate site stuck inside of an iframe.

**Comment by chriscoyier** [comment]
There are going to be 150 videos in the Lodge area of the site that detail every single decision made and how it was done. Totally appreciate the feedback and you are free to dislike it all you want, but I'm going to keep this GitHub area for literal bugs in the site.

**Comment by chrisjaure** [comment]
Ok, sorry about that. UX issues are still bugs though.

**Comment by chriscoyier** [comment]
Absolutely! I'd love all reports of UX issues.

**Comment by chrisjaure** [comment]
K, I'll try to distill this down into a useful and actionable UX issue (though UX is more subjective than a literal bug and you still might not agree).

Going with the consistency theme, I'll focus on the choice of pagination patterns. Usually, it's at the top and bottom, and for numbered pages, usually it uses digits. I feel the pages that deviate from that pattern are harder to use.

Here are some examples: the videos section uses Greek numerals spelled out instead of digits; the forum section only has pagination on the bottom; the snippets page could also conform to the common pagination pattern, but I can see benefits to the way it is now as well (more room for future categories), though at the cost of consistency.

So to conclude, I think a more cohesive UX could be achieved if one pagination pattern was used where possible.

**Comment by chriscoyier** [comment]
That's an interesting one because I literally went though quite a bit of work specifically on pagination and making it as consistant as I could. There are pretty specific reasons for each single navigation and pagination choice. I go through a ton of the thinking behind every single one in the video series. Perhaps it will make a good blog post someday as well.
