### ISSUE TITLE
Gallery loading indicator

### ISSUE THREAD

**Issue by chrisjaure** [chriscoyier/CSS-Tricks-v10#56]
Each gallery page takes a bit (2-4 seconds) to load completely for me. While the main page loads right away, the actual images don't and it looks broken until they do. Maybe throw in a spinny gif that shows initially and gets replaced by the images once they load?

**Comment by chriscoyier** [comment]
I like it! Will do, great idea.

**Comment by chriscoyier** [comment]
Related to this, I have developed a way to make the grid of images load in nicer, but it involves knowing the image dimensions server-side, which I don't really have. If I can figure out a good way to save that data, I can get it in there. 

Kinda like -- http://codepen.io/chriscoyier/pen/vfhgF

**Comment by chriscoyier** [comment]
Added!

**Comment by chrisjaure** [comment]
Nice, looks good :)
