### ISSUE TITLE
A few minor styling problems. Super minor.

### ISSUE THREAD

**Issue by ryanburnette** [chriscoyier/CSS-Tricks-v10#58]
I was on the train playing with v10 on my iPhone using Chrome for iOS and noticed these tiny little things. They're so so small but I figured I'd post them. I hope I'm not being annoying.

![ss1](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-06-chrome-ios-styling/input-fields.png)
These input fields looked like something was a little out of place. I assumed the text would be vertically set to middle, not top.

![ss2](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-06-chrome-ios-styling/radio-buttons.png)
These radio buttons were cut off on their bottoms. Poor little radio buttons.

![ss3](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-06-chrome-ios-styling/this-bug-is-probably-chrome-not-the-site.png)
And here, when you go into the change tabs view some elements that are normally hidden strangely appear. This is probably a bug in Chrome, not the site, but I thought it was interesting.

**Comment by ryanburnette** [comment]
![ss1](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-forum-textarea-container/forum-textarea-container.png)
On the forum you can expand the textareas outside their containers. Setting the max-width property would fix this.

**Comment by chriscoyier** [comment]
Confirmed all. Will fix all of them.

I THINK there is a css property for controlling resizing of textareas on only Y axis.

**Comment by ryanburnette** [comment]
max-width is what I always set, if you find a better way I'd love to know

On Fri, Sep 7, 2012 at 7:28 PM, Chris Coyier notifications@github.comwrote:

> Confirmed all. Will fix all of them.
> 
> I THINK there is a css property for controlling resizing of textareas on
> only Y axis.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chriscoyier/CSS-Tricks-v10/issues/58#issuecomment-8382027.

## 

_Ryan Burnette_

TechStudio #TECHSEO

http://techstudio.co
http://techseo.co

+1 (877) 793-0670 office (voice)
+1 (323) 546-7926 direct (voice, sms)

ryan@techstudio.co
service@techseo.co

**Comment by FelixKiunke** [comment]
Yes, there is a `resize` property which is supported unprefixed in all browsers supporting resizing text fields according to http://caniuse.com/#feat=css-resize
Just set `resize: none | both | horizontal | vertical` :)

**Comment by chriscoyier** [comment]
I think I got all these fixed. Plz reopen new ticket if you see any of them persist.

**Comment by ryanburnette** [comment]
What method did you use to limit the size of the textareas?

On Wed, Sep 12, 2012 at 7:37 PM, Chris Coyier notifications@github.comwrote:

> I think I got all these fixed. Plz reopen new ticket if you see any of
> them persist.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chriscoyier/CSS-Tricks-v10/issues/58#issuecomment-8513920.

## 

_Ryan Burnette_

TechStudio #TECHSEO

http://techstudio.co
http://techseo.co

+1 (877) 793-0670 office (voice)
+1 (323) 546-7926 direct (voice, sms)

ryan@techstudio.co
service@techseo.co
