### ISSUE TITLE
Issues with Firefox 15 on Mac 10.8.1

### ISSUE THREAD

**Issue by erunyon** [chriscoyier/CSS-Tricks-v10#6]
1. Font icons not showing
2. word-break: break-all; on body is making the content hard to read

**Comment by jcsrb** [comment]
+1 FF 15 Ubuntu http://i.imgur.com/Vuhpp.png

**Comment by phph** [comment]
+1 FF 15 on Mac OS X 10.5.8

**Comment by davezatch** [comment]
+1 FF16 on Windows 7

**Comment by ajmarino** [comment]
+1 for the icons, also the list of links in the footer are missing the lines and hover effect that show up in chrome 21 on OS X 10.8.1

**Comment by KittyGiraudel** [comment]
+1 Firefox Aurora 17 on Windows XP.

**Comment by jcsrb** [comment]
has been fixed, works on my FF15/Ubuntu

**Comment by erunyon** [comment]
Fixed for me now too.

**Comment by chriscoyier** [comment]
Word break fix going out now.
