### ISSUE TITLE
Chrome bugs

### ISSUE THREAD

**Issue by gruber76** [chriscoyier/CSS-Tricks-v10#60]
In Chrome (21.0.1180.89 m on Windows 8 Release Preview,) when I resize the browser down I occasionally get a glitch.  The layout starts to jump rapidly back and forth between states.  The first time it happened, I had to close my tab in order to get it to stop strobing.  The second time it stuck on a narrow (iPhone?) width even when the browser was wider.

**Comment by chriscoyier** [comment]
Yeah I get that sometimes too. I suspect it's too much awesomeness.

(but really,  it's probably all the box shadows and media queries and stuff)

I'm gonna lump this in with the scrolling issue too. I imagine fixing that will help this too.
