### ISSUE TITLE
Native browser error message for input="search"

### ISSUE THREAD

**Issue by kimroen** [chriscoyier/CSS-Tricks-v10#61]
The default error notification for input="search" goes underneath the navigation.
Screenshot:
![Screenshot from css-tricks](http://f.cl.ly/items/0L0n131o1w2V0w2i0z2I/Skjermbilde%202012-09-07%20kl.%2009.41.18.png)

I'm using Chrome Canary.
This is in norwegian, but it says "Please fill in this field".

**Comment by chriscoyier** [comment]
Fixed
