### ISSUE TITLE
Body font text in Chrome on WinXP is barely readable

### ISSUE THREAD

**Issue by johnasp** [chriscoyier/CSS-Tricks-v10#63]
I have noticed this on a few sites for the body font text where the font is rendered really thin, jagged and barely readable.  Smashing Magazine also has this problem so you're not alone!  Firefox renders it fine though on my XP machine

**Comment by BeingTomGreen** [comment]
Which version of Chrome are you running? I am running the latest stable version, and don't see any issues on CSS Tricks or Smashing magazine on my XP box!

**Comment by jgclifton** [comment]
Isn't this a bug to do with graphics acceleration?

**Comment by ryanburnette** [comment]
It looks pretty good to me (see screenshots), not great though. I've dealt with this problem before. It's very difficult to write contingencies to deal with poor font smoothing that's happening at the OS. I use browser.php to detect and make changes based on the OS though.

![ss1](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-windows-xp-chrome/windows-xp-chrome.png)

![ss2](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-windows-xp-chrome/chrome-version.png)

I can work with a set of information like this and assuming that it's possible on an old OS that fonts may not smooth properly, I switch them out for web safe. Even on Typekit, a lot of fonts garble on an old OS.

`Browser Object
(
    [_agent:Browser:private] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
    [_browser_name:Browser:private] => Chrome
    [_version:Browser:private] => 21.0.1180.89
    [_platform:Browser:private] => Apple
    [_os:Browser:private] => unknown
    [_is_aol:Browser:private] => 
    [_is_mobile:Browser:private] => 
    [_is_robot:Browser:private] => 
    [_aol_version:Browser:private] => unknown
)`

**Comment by chriscoyier** [comment]
Just changed the body font, lemme know if better

**Comment by ryanburnette** [comment]
I think the new font looks better all-around, but especially in Windows XP.

![new](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-windows-xp-chrome/chrome-xp-new-font.png)

**Comment by johnasp** [comment]
Just checked this morning at work on my crappy XP machine and it's looks lots better, I can read the text now!
