### ISSUE TITLE
Image missing on the profil page 

### ISSUE THREAD

**Issue by Luxbit** [chriscoyier/CSS-Tricks-v10#64]
There's an image missing on the profil page (http://css-tricks.com/forums/profile/) 

  img src="/forums/uploads/"    <---missing  // line  171

**Comment by chriscoyier** [comment]
yeah that's definitely a bug. Finding it hard to track down... I'll get it though. Worst case scenario I have to show gravatar only.

**Comment by chriscoyier** [comment]
Fixed!
