### ISSUE TITLE
Firefox 15.0.1 Footer Area

### ISSUE THREAD

**Issue by JudgmentDay** [chriscoyier/CSS-Tricks-v10#68]
Hello,

Two things regarding the footer area for Firefox 15.0.1 as of 11:30AM:

1) The dark grey background, which was there during relaunch, seems to be missing now. Not sure what happened.

2) For all of the text links on the left and right sides, you seem to have a light effect on hover, which is fine. However, you can hover beyond the text more towards the center which creates a small link detect from the empty span tags. Moving your mouse around this area creates almost a flicker effect between the pointer and default cursor. I'm not sure if this was the intent of the functionality. Firefox in particular doesn't have this effect at all, but still contains the odd hit states.

**Comment by JudgmentDay** [comment]
Okay, after looking at a couple of pages, issue #1 only seems to happen in Firefox when viewing the V10 Blog Post:
http://css-tricks.com/design-v10/

So I'm not sure if this is worth looking at, but if it's suspect to happen on one page, it has odds of appearing again on certain conditions.

**Comment by chriscoyier** [comment]
I'm not sure I totally get it. Is it still a problem? Could you try and re-explain?
