### ISSUE TITLE
/design-v10/ Blog Post: iPhone

### ISSUE THREAD

**Issue by JudgmentDay** [chriscoyier/CSS-Tricks-v10#69]
Not sure what's causing this, but loading the Design v10 Blog Post causes Safari to crash on the iPhone. At times, the other saved windows that were used while browsing, including css-tricks.com fail to recover upon relaunch.

http://css-tricks.com/design-v10/

iOS Version 5.1.1 (9B206)

**Comment by ryanburnette** [comment]
This happens for me as well. iOS Version 5.1.1 (9B206)

**Comment by chriscoyier** [comment]
Closing as duplicate, thanks!
