### ISSUE TITLE
Image on Lodge page links to localhost

### ISSUE THREAD

**Issue by mattbanks** [chriscoyier/CSS-Tricks-v10#7]
There is an image on [The Lodge](http://css-tricks.com/lodge/) that is linking to `localhost`, right after the paragraph:

"How about a graphic to sum that all up:"

Current link: http://localhost/wp-content/uploads/2012/08/learningz.jpg

Should be: http://css-tricks.com/wp-content/uploads/2012/08/learningz.jpg

**Comment by chriscoyier** [comment]
Should be fixed, thanks.
