### ISSUE TITLE
Word Wrapping Problems

### ISSUE THREAD

**Issue by cnwtx** [chriscoyier/CSS-Tricks-v10#70]
I'm seeing everywhere that a new line falls in the middle of a word, it just splits the word, no hyphen or anything. I'm using FF 15 on Ubuntu 12.04

**Comment by chriscoyier** [comment]
I removed the word-breaking stuff, so lemme know if this is somehow still and issue and hit me with a screenshot.

**Comment by cnwtx** [comment]
That fixed it! Thanks!
