### ISSUE TITLE
Forum: When making an additional comment, the textarea's height is reduced to 0.

### ISSUE THREAD

**Issue by ryanburnette** [chriscoyier/CSS-Tricks-v10#71]
I looked and didn't see this issue posted by anyone else, I hope I wasn't unobservant.

When trying to write an additional post on the forum (I'm using up-to-date Chrome on Mac OS 10.8.1) the textarea shrinks its height to 0 as soon as I begin typing.

![before typing](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-forum-textarea/forum-textarea-1.png)

![after typing](https://dl.dropbox.com/u/8483722/css-tricks/2012-09-07-forum-textarea/forum-textarea-2.png)

**Comment by KittyGiraudel** [comment]
Happened to me once or twice. A refresh "fixed" the problem, but the issue remains randomly.

**Comment by chriscoyier** [comment]
I think this is fixed now. I've strong-handed the JS out of the forums so it reallllly shouldn't be happening. Lemme know if you ever see it again (after cache flush, refresh).
