### ISSUE TITLE
Version 9 Styling Still Present in Demos

### ISSUE THREAD

**Issue by ghost** [chriscoyier/CSS-Tricks-v10#75]
On the demos for articles and downloads, I noticed that the v9 style is still applied to the top header.

Example: http://css-tricks.com/examples/ConvertMenuToDropdown/ (the 'A CSS-Tricks Example' banner)

**Comment by chriscoyier** [comment]
Yes! That needs to be redesigned for sure.

**Comment by chriscoyier** [comment]
Note to self: make sure to update header on fluid width videos demo

**Comment by chriscoyier** [comment]
done
