### ISSUE TITLE
Update apple touch icons

### ISSUE THREAD

**Issue by chriscoyier** [chriscoyier/CSS-Tricks-v10#78]

**Comment by chriscoyier** [comment]
done

**Comment by joshbetz** [comment]
Not positive, but I don't think you have a 114x114 apple-touch-icon.

**Comment by chriscoyier** [comment]
I do actually. does it not appear to be working? What are the symptoms?

**Comment by joshbetz** [comment]
I tried to save it the the homescreen on my iPhone just to test it and it looked like it might not be retina. I see: `<link rel="apple-touch-icon" href="/apple-touch-icon.png">` in the HTML, but that icon is 57x57.

**Comment by chriscoyier** [comment]
Interesting. I have all the ones in place that the HTML5 Boilerplate recommends: http://cl.ly/JX3x

I guess you need to make "apple-touch-icon.png" the 114x114 one, instead of the 57x57 one like they have it. I'll try that and see if it works.

**Comment by joshbetz** [comment]
I'm pretty sure you can either have one icon that is 114x114 that gets served to everything, or specify them all separately: http://developer.apple.com/library/ios/#DOCUMENTATION/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by chriscoyier** [comment]
Just made it 114x and it's solid. Thanks!
