### ISSUE TITLE
inventory.markdown file link connects to an xml file in safari

### ISSUE THREAD

**Issue by kikodoran** [chriscoyier/CSS-Tricks-v10#82]
Not sure why but the inventory.markdown file won't download in Safari.

Running:
MBP Retina
OSX 10.8.1
Safari Version 6.0 (8536.25)

Worked fine in Chrome though...

Thanks for doing such an awesome job! Hope you do this Kickstarter thing again!

**Comment by chriscoyier** [comment]
Can you try refreshing the page a few times (maybe a full cache flushing) and re-trying? I've heard this issue before but that seemed to fix it for them.

**Comment by kikodoran** [comment]
Works perfectly after refresh. Haven't run in to that issue before.
