### ISSUE TITLE
Videos do not load on iPad (3)

### ISSUE THREAD

**Issue by Darfuria** [chriscoyier/CSS-Tricks-v10#87]
In either orientation. Just get the CSS-Tricks background, or sometimes a black square. Audio files play intermittently.

**Comment by chriscoyier** [comment]
Should be fixed. Although I had to start using .mp4 and the file sizes are quite a bit bigger. Should be good quality though.

**Comment by pfortes** [comment]
I still can't load the lodge videos in my retina iPad !!

**Comment by Darfuria** [comment]
Me neither - I get the player GUI, but when I press play the loading animation plays continuously.
