### ISSUE TITLE
Problems with Videos in the Lodge

### ISSUE THREAD

**Issue by rrjmdpa** [chriscoyier/CSS-Tricks-v10#88]
I've emailed about specific problems - but see this problem repository so I'll create a record here for you.

1 - I see previous comments about MIME types and that you indicated it was fixed.  However, I'm still noting existing problems in FireFox (v15) and IE9.

2 - **[Correct MIME type for #1]** Screencast #1 - views fine in FF15 - But only presents a large background image with no apparent player in IE9.

3 - **[Incorrect MIME type for FF or IE]** No other screencast will play correctly in FF15.

4 - **[Audio MIME type FF]** The audio cast - plays automatically and correctly in IE9; Does **not** in FF15 - although the "download" button causes it to play.

5 - **[No control over "download"]** Using the "download" button it both FF15 and IE9 - does **not** "download" in the usual sense. Neither of them offer a "save" or "run" options as is usual and customary.

6 - **[No Controls]** Only the very first video can be played in a "normal" player after downloading in both FF15 and IE9.  All the rest (so far) open in quicktime player - automatically in **full screen** (no options) and **there are no controls!**. So only pause (single click) and restart (double click) are available but without any instructions.  There is no option to shrink or expand, and no ability to replay a section for clarity, NOR the ability to skip forward past parts you've already seen or don't want to view.

It seems as though you've used different code for MIME types and even the player for the 1st screencast than you used for the rest of them.  Seems like it should be consistent - really, anything short of directly playing in a player that has controls is really sub-optimal.

**Comment by chriscoyier** [comment]
All the videos use the exact same template and the exact same MIME type. MIME type is set by the .htaccess file on the site and I couldn't control them individually if I wanted to. 

My plan is to toss in http://mediaelementjs.com/ in the next few days which should be a nicer placer.
