### ISSUE TITLE
Video Loading Issues in Lodge - Google Chrome 21.0.1180.89 & Windows 7

### ISSUE THREAD

**Issue by grayghostvisuals** [chriscoyier/CSS-Tricks-v10#89]
### Platform

Windows 7 and Google Chrome 21.0.1180.89 m via wi-fi
#### Video 6,7,10

I had to refresh the browser 5 times to get the video to play. However, for video 6, I dragged the scrubber slightly to the right and viola! the video began
#### Video 9,10

No full screen option

**Comment by chriscoyier** [comment]
New video player is up, should fix these issues.
