### ISSUE TITLE
Words being split on lines.

### ISSUE THREAD

**Issue by trentwritescode** [chriscoyier/CSS-Tricks-v10#9]
Hey Chris. I love the redesign but I'm definitely being thrown off by words that are split between lines. For example, the word woodchuck is divided with "woodc" at the end of one line and then "huck" at the beginning of the line below that.

I'm using the latest release of Mozilla Firefox.

**Comment by jtojnar** [comment]
I have this problem too (Firefox 15, Ubuntu) and other people have this too: #11, #20, #25
