### ISSUE TITLE
Issue with 'View Comments' in Mobile version.

### ISSUE THREAD

**Issue by pankajparashar-zz** [chriscoyier/CSS-Tricks-v10#93]
On Galaxy S3 Android OS (Chrome) when clicked on 'View Comments' it takes the scrolls the page right to the top & the comments section doesn't load...

**Comment by chriscoyier** [comment]
May need a refresh or two? It's brand new earlier today, to prevent some crashing issues. 

Screenshot perhaps too? I can't quite picture your words here.

**Comment by pankajparashar-zz** [comment]
Apologies for the incorrect English! (I lodged the issue on mobile) ...The 'View Comments' section doesn't load when i click on it, instead the page scrolls right to the top.

Is it just me, who is facing this issue?
