### ISSUE TITLE
Strange ordering of video number on Video Screencasts page

### ISSUE THREAD

**Issue by mwseymour** [chriscoyier/CSS-Tricks-v10#95]
When viewing this page http://css-tricks.com/video-screencasts/page/5/  the video numbers are in order from highest to lowest but some random videos seem to be interjected. I may have just missed the point on this but thought I would submit in case.

Chrome 21
Mac OS X 10.8.1

EDIT:

Seems to be First and last videos + the video after the page break of ads

**Comment by chriscoyier** [comment]
Sorted out, thanks
