### ISSUE TITLE
The Lodge 'play' Buttons - Usability Issues w/ Quick Mouse Clicks

### ISSUE THREAD

**Issue by grayghostvisuals** [chriscoyier/CSS-Tricks-v10#98]
MAC OS 10.7.4 Lion - Google Chrome Version 21.0.1180.89

There are usability issues with the 'play' buttons for the lodge's projects item summary. Sometimes they require two clicks and other times one gigantic hard click with the mouse. 

Quick mouse clicks just don't register unless the button was clicked previously or already visited.

**Comment by chriscoyier** [comment]
Maybe screencast it quick? http://www.screenr.com/

As you probably know, there isn't like "hardclick" events on the web, it's just click or not =)  

And let me know exactly what buttons you are talking about. The play ones here on the list of all videos? http://css-tricks.com/lodge/v10/

**Comment by grayghostvisuals** [comment]
> earlier comments :
> And let me know exactly what buttons you are talking about. The play ones here on the list of all videos? http://css-tricks.com/lodge/v10/

Yeah those ones
